addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.28")
addSbtPlugin("com.vmunier"        % "sbt-web-scalajs"          % "1.0.9-0.6")

addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.25")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "0.14.10")

addSbtPlugin("com.dwijnand"   % "sbt-dynver"   % "4.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.5")
//addSbtPlugin("com.jsuereth"     % "sbt-pgp"      % "2.0.0-M2")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"        % "1.1.2-1")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"        % "1.0.0")
addSbtPlugin("com.47deg"        % "sbt-microsites" % "0.9.2")
//addSbtPlugin("org.scalameta" % "sbt-mdoc"      % "1.3.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"  % "2.0.2")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.0")
